// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieF378rpLiIvEXa_jhbbA4bbxYgNrDEg',
    appId: '1:801044998395:web:d65a4218b8aebf6f24e85e',
    messagingSenderId: '801044998395',
    projectId: 'mandangon-90611',
    authDomain: 'mandangon-90611.firebaseapp.com',
    storageBucket: 'mandangon-90611.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXtQfdDcsyZrQI9kk_8lOQCbeC1F2MbPM',
    appId: '1:801044998395:android:cf0199536220338d24e85e',
    messagingSenderId: '801044998395',
    projectId: 'mandangon-90611',
    storageBucket: 'mandangon-90611.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0cdTIWJfe5wyIMssZB29yi9I7Gx-vPhk',
    appId: '1:801044998395:ios:10f09f02940ca93024e85e',
    messagingSenderId: '801044998395',
    projectId: 'mandangon-90611',
    storageBucket: 'mandangon-90611.firebasestorage.app',
    iosBundleId: 'com.example.mandangon',
  );

}